import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "./navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PJATK Quiz App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <hr style={{ margin: 40}}></hr>
        {children}
      </body>
    </html>
  );
}
