import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppBar, Toolbar } from "@mui/material";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PJATK Quiz App",
  description: "Generated by create next app",
};

const links = [
  {
    href: "/",
    title: "home"
  },
  {
    href: "/creator",
    title: "creator"
  }
]
export function Navbar() {
  return (
    <AppBar>
      <Toolbar sx={{ flex:1, justifyContent:'center'}}>
      {links.map(item => {
        return(
         <Link href={item.href} style={{ textDecoration: 'none', margin: 20, color:'white' }}>
            {item.title}
         </Link>
        ) 
        })
      }
      </Toolbar>
    </AppBar>
  )
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <hr style={{ margin: 40}}></hr>
        {children}
      </body>
    </html>
  );
}
